#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile pipenv

  ln -nfs "$(pipenv run which sam)" "$shome/bin/sam"
}

main "$@"
